# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import ujson
import csv
import subprocess
import cv2
from PIL import Image, ImageTk
import threading
import sys
import os
import numpy as np

current_dir = os.path.dirname(os.path.abspath(__file__))

project_root = os.path.abspath(os.path.join(current_dir, '../../'))

sys.path.insert(0, project_root)

import thesystem.system
import thesystem.inventory

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")

with open("Files/Player Data/Tabs.json",'r') as tab_son:
    tab_son_data=ujson.load(tab_son)

with open("Files/Player Data/Tabs.json",'w') as fin_tab_son:
    tab_son_data["Inventory"]='Open'
    ujson.dump(tab_son_data,fin_tab_son,indent=4)

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

initial_height = 0
target_height = 568
window_width = 855

window.geometry(f"{window_width}x{initial_height}")
thesystem.system.make_window_transparent(window)
subprocess.Popen(['python', 'Files/Mod/default/sfx.py'])
thesystem.system.animate_window_open(window, target_height, window_width, step=30, delay=1)

window.configure(bg = "#FFFFFF")
set_data=thesystem.misc.return_settings()
transp_value=set_data["Settings"]["Transparency"]

window.attributes('-alpha',transp_value)
window.overrideredirect(True)
window.wm_attributes("-topmost", True)

def start_move(event):
    window.lastx, window.lasty = event.widget.winfo_pointerxy()

def move_window(event):
    x_root, y_root = event.widget.winfo_pointerxy()
    deltax, deltay = x_root - window.lastx, y_root - window.lasty

    if deltax != 0 or deltay != 0:  # Update only if there is actual movement
        window.geometry(f"+{window.winfo_x() + deltax}+{window.winfo_y() + deltay}")
        window.lastx, window.lasty = x_root, y_root


def ex_close(win):
    with open("Files/Player Data/Tabs.json",'r') as tab_son:
        tab_son_data=ujson.load(tab_son)

    with open("Files/Player Data/Tabs.json",'w') as fin_tab_son:
        tab_son_data["Inventory"]='Close'
        ujson.dump(tab_son_data,fin_tab_son,indent=4)
    threading.Thread(target=thesystem.system.fade_out, args=(window, 0.8)).start()
    subprocess.Popen(['python', 'Files/Mod/default/sfx_close.py'])
    thesystem.system.animate_window_close(window, initial_height, window_width, step=50, delay=1)

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 568,
    width = 855,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    679.0,
    364.0,
    image=image_image_1
)

with open("Files/Mod/presets.json", 'r') as pres_file:
    pres_file_data=ujson.load(pres_file)
    video_path=pres_file_data["Manwha"]["Video"]
    preloaded_frames=np.load(video_path)
player = thesystem.system.FastVideoPlayer(canvas, preloaded_frames, 400.0, 300.0, resize_factor=1.2)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    427.0,
    284.0,
    image=image_image_2
)

canvas.create_rectangle(
    23.0,
    136.0,
    832.0,
    473.0,
    fill="#040404",
    outline="")

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    46.0,
    124.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    134.0,
    66.0,
    image=image_image_4
)

with open("Files/Player Data/Inventory.json", 'r') as fson:
    data=ujson.load(fson)

rol=list(data.keys())

button_images = []
item_images = []

x_start, y_start = 49, 171
spacing_x, spacing_y = 100, 100
buttons_per_row = 8

image5=relative_to_assets("image_5.png")

for i, key in enumerate(rol[:24]):
    item_data = {
        "name": key,
        "tr_n":thesystem.inventory.inventory_name_cut(key),
        "qty": data[key][0].get('qty', ''),
        "cat": data[key][0].get('cat', ''),
        "rank": data[key][0].get('rank', ''),
        "desc": data[key][0].get('desc', ''),
        "buff": data[key][0].get('buff', ''),
        "debuff": data[key][0].get('debuff', '')
    }
    x = x_start + (i % buttons_per_row) * spacing_x
    y = y_start + (i // buttons_per_row) * spacing_y
    thesystem.inventory.create_inventory_item(canvas, window, item_data, x, y, button_images, item_images, image5)

image_image_29 = PhotoImage(
    file=relative_to_assets("image_29.png"))
image_29 = canvas.create_image(
    427.0,
    10.0,
    image=image_image_29
)

canvas.tag_bind(image_29, "<ButtonPress-1>", start_move)
canvas.tag_bind(image_29, "<B1-Motion>", move_window)

button_image_25 = PhotoImage(
    file=relative_to_assets("button_25.png"))
button_25 = Button(
    image=button_image_25,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: ex_close(window),
    relief="flat"
)
button_25.place(
    x=806.0,
    y=30.0,
    width=20.0,
    height=20.0
)
window.resizable(False, False)
window.mainloop()
