
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import csv
import ujson
import subprocess

subprocess.Popen(['python', 'Files/Mod/default/sfx.py'])

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("555x687")
window.configure(bg = "#FFFFFF")
window.attributes('-alpha',0.8)

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 687,
    width = 555,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    277.0,
    350.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    293.0,
    345.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    205.0,
    74.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    293.0,
    228.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    293.0,
    200.0,
    image=image_image_5
)

canvas.create_text(
    275.0,
    186.0,
    anchor="nw",
    text="???",
    fill="#FFFFFF",
    font=("Montserrat Bold", 20 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    292.63682556152344,
    284.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    130.0,
    283.0,
    image=image_image_7
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=148.0,
    y=253.0,
    width=12.0,
    height=12.0
)

canvas.create_text(
    58.0,
    306.0,
    anchor="nw",
    text="ITEM NAME -1",
    fill="#FFFFFF",
    font=("Montserrat Bold", 12 * -1)
)

canvas.create_text(
    60.0,
    321.0,
    anchor="nw",
    text="-BUFF A1",
    fill="#18FF59",
    font=("Montserrat Regular", 12 * -1)
)

canvas.create_text(
    60.0,
    336.0,
    anchor="nw",
    text="-BUFF A2",
    fill="#18FF59",
    font=("Montserrat Regular", 12 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    293.0,
    380.0,
    image=image_image_8
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=299.0,
    y=343.0,
    width=12.0,
    height=12.0
)

canvas.create_text(
    258.0,
    403.0,
    anchor="nw",
    text="ITEM NAME -2",
    fill="#FFFFFF",
    font=("Montserrat Bold", 12 * -1)
)

canvas.create_text(
    260.0,
    418.0,
    anchor="nw",
    text="-BUFF B1",
    fill="#18FF59",
    font=("Montserrat Regular", 12 * -1)
)

canvas.create_text(
    260.0,
    433.0,
    anchor="nw",
    text="-BUFF B2",
    fill="#18FF59",
    font=("Montserrat Regular", 12 * -1)
)

canvas.create_text(
    434.0,
    309.0,
    anchor="nw",
    text="ITEM NAME -3",
    fill="#FFFFFF",
    font=("Montserrat Bold", 12 * -1)
)

canvas.create_text(
    436.0,
    324.0,
    anchor="nw",
    text="-BUFF C1",
    fill="#18FF59",
    font=("Montserrat Regular", 12 * -1)
)

canvas.create_text(
    436.0,
    339.0,
    anchor="nw",
    text="-BUFF C2",
    fill="#18FF59",
    font=("Montserrat Regular", 12 * -1)
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    455.0,
    283.0,
    image=image_image_9
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=427.0,
    y=254.0,
    width=12.0,
    height=12.0
)

canvas.create_text(
    55.0,
    479.0,
    anchor="nw",
    text="COMPLETE SET EFFECT BONUS:",
    fill="#FFFFFF",
    font=("Montserrat SemiBold", 15 * -1)
)

canvas.create_text(
    89.0,
    504.0,
    anchor="nw",
    text="-FINAL BUFF 1",
    fill="#18FF59",
    font=("Montserrat Medium", 12 * -1)
)

canvas.create_text(
    89.0,
    540.0,
    anchor="nw",
    text="-FINAL BUFF 3",
    fill="#18FF59",
    font=("Montserrat Medium", 12 * -1)
)

canvas.create_text(
    89.0,
    522.0,
    anchor="nw",
    text="-FINAL BUFF 2",
    fill="#18FF59",
    font=("Montserrat Medium", 12 * -1)
)

canvas.create_text(
    183.0,
    504.0,
    anchor="nw",
    text="COMPLETE SET HAS NOT BEEN UNLOCKED! ",
    fill="#FF2424",
    font=("MontserratItalic Medium", 12 * -1)
)

canvas.create_text(
    183.0,
    518.0,
    anchor="nw",
    text="FIND ALL THE ITEMS OF THE SET TO REAP ITS BONUS!",
    fill="#FF2424",
    font=("MontserratItalic Medium", 12 * -1)
)
window.resizable(False, False)
window.mainloop()
