
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import json
import csv
from datetime import datetime, timedelta
import subprocess
import threading
import pandas as pd
import sys
import os

current_dir = os.path.dirname(os.path.abspath(__file__))

project_root = os.path.abspath(os.path.join(current_dir, '../../'))

sys.path.insert(0, project_root)

import thesystem.system

with open("Files\Mod\presets.json", 'r') as pres_file:
    pres_file_data=json.load(pres_file)
    get_stuff_path_str=pres_file_data["Anime"]["Message Box"]

def get_stuff_path(key):
    full_path=get_stuff_path_str+'/'+key
    return full_path

window = Tk()

initial_height = 0
target_height = 144
window_width = 715

window.geometry(f"{window_width}x{initial_height}")
thesystem.system.make_window_transparent(window)
thesystem.system.animate_window_open(window, target_height, window_width, step=35, delay=1)

window.configure(bg = "#FFFFFF")
window.attributes('-alpha',0.8)
window.overrideredirect(True)
window.wm_attributes("-topmost", True)

top_images = [f"thesystem/top_bar/dailyquest.py{str(i).zfill(4)}.png" for i in range(1, 501)]
bottom_images = [f"thesystem/bottom_bar/{str(i).zfill(4)}.png" for i in range(1, 501)]

# Preload top and bottom images
top_preloaded_images = thesystem.system.preload_images(top_images, (715, 35))
bottom_preloaded_images = thesystem.system.preload_images(bottom_images, (715, 41))

subprocess.Popen(['python', 'Files\Mod\default\sfx.py'])

def start_move(event):
    global lastx, lasty
    lastx = event.x_root
    lasty = event.y_root

def move_window(event):
    global lastx, lasty
    deltax = event.x_root - lastx
    deltay = event.y_root - lasty
    x = window.winfo_x() + deltax
    y = window.winfo_y() + deltay
    window.geometry("+%s+%s" % (x, y))
    lastx = event.x_root
    lasty = event.y_root

def ex_close(win):
    threading.Thread(target=thesystem.system.fade_out, args=(window, 0.8)).start()
    subprocess.Popen(['python', 'Files\Mod\default\sfx_close.py'])
    thesystem.system.animate_window_close(window, initial_height, window_width, step=35, delay=1)

def get_item_name_from_csv():
    # Read the item name from the CSV file
    with open('Files/Data/lowest_rank_item.csv', 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            return row['Name']

rank='X'

item_name = get_item_name_from_csv()
with open('Files/Inventory.json', 'r') as file:
    data = json.load(file)

# Find the item and update or remove it
if item_name in data:
    for item in data[item_name]:
        rank=item["rank"]

def update_inventory():
    # Get the item name from the CSV file
    item_name = get_item_name_from_csv()

    # Load the JSON data from the file
    with open('Files/Inventory.json', 'r') as file:
        data = json.load(file)
    
    # Find the item and update or remove it
    if item_name in data:
        for item in data[item_name]:
            if item['qty'] == 1:
                # Remove the item if quantity is 1
                data[item_name].remove(item)
            elif item['qty'] > 1:
                # Decrease quantity by 1 if greater than 1
                item['qty'] -= 1

        # If all instances are removed, delete the item from inventory
        if not data[item_name]:
            del data[item_name]

    # Write the updated data back to inventory.json
    with open('Files/Inventory.json', 'w') as file:
        json.dump(data, file, indent=4)

    rank=item["rank"]
    with open("Files\Data\Todays_Dungeon.json", 'r') as dun_full:
        dun_full_data=json.load(dun_full)

    with open("Files\Data\Dungeon_Rank.csv", 'w', newline='') as rank_file:
        fw=csv.writer(rank_file)
        fw.writerow([rank,"Instance"])

    with open("Files\Data\Todays_Dungeon.json", 'w') as final_dun_full:
        json.dump(dun_full_data, final_dun_full, indent=6)

    subprocess.Popen(['python', 'Anime Version/Dungeon Runs/gui.py'])
    window.quit()

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 144,
    width = 715,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=get_stuff_path("back.png"))
image_1 = canvas.create_image(
    448.0,
    277.0,
    image=image_image_1
)

with open("Files\Mod\presets.json", 'r') as pres_file:
    pres_file_data=json.load(pres_file)
    normal_font_col=pres_file_data["Anime"]["Normal Font Color"]
    video_path=pres_file_data["Anime"]["Video"]
player = thesystem.system.VideoPlayer(canvas, video_path, 478.0, 330.0, resize_factor=0.8)

image_image_2 = PhotoImage(
    file=get_stuff_path("frame.png"))
image_2 = canvas.create_image(
    357.0,
    78.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=get_stuff_path("enter_txt.png"))
image_3 = canvas.create_image(
    363.0,
    56.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=get_stuff_path("close.png"))
image_4 = canvas.create_image(
    596.0,
    53.0,
    image=image_image_4
)

canvas.tag_bind(image_4, "<ButtonPress-1>", ex_close)

canvas.create_text(
    264.0,
    65.0,
    anchor="nw",
    text=f"{rank}-Rank Instance Dungeon",
    fill="#45EF2A",
    font=("Montserrat Regular", 15 * -1)
)

button_image_1 = PhotoImage(
    file=get_stuff_path("yes.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: update_inventory(),
    relief="flat"
)
button_1.place(
    x=212.0,
    y=90.0,
    width=68.0,
    height=17.0
)

button_image_2 = PhotoImage(
    file=get_stuff_path("no.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: ex_close(window),
    relief="flat"
)
button_2.place(
    x=445.0,
    y=90.0,
    width=68.0,
    height=17.0
)

side = PhotoImage(file=get_stuff_path("blue.png"))
canvas.create_image(677.0, 71.0, image=side)
canvas.create_image(47.0, 72.0, image=side)

canvas.create_rectangle(
    0.0,
    0.0,
    760.0,
    30.0,
    fill="#0C679B",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    162.0,
    16.0,
    fill="#0C679B",
    outline="")

canvas.create_rectangle(
    0.0,
    123.0,
    715.0,
    144.0,
    fill="#0C679B",
    outline="")

image_40 = thesystem.system.side_bar("left_bar.png", (30, 100))
canvas.create_image(82.0, 76.0, image=image_40)

image_50 = thesystem.system.side_bar("right_bar.png", (30, 114))
canvas.create_image(640.0, 75.0, image=image_50)

image_index = 0
bot_image_index = 0

top_image = canvas.create_image(
    357.0,
    20.0,
    image=top_preloaded_images[image_index]
)

canvas.tag_bind(top_image, "<ButtonPress-1>", start_move)
canvas.tag_bind(top_image, "<B1-Motion>", move_window)

bottom_image = canvas.create_image(
    370.0,
    128.0,
    image=bottom_preloaded_images[bot_image_index]
)

step,delay=1,1

def update_images():
    global image_index, bot_image_index

    # Update top image
    image_index = (image_index + 1) % len(top_preloaded_images)
    canvas.itemconfig(top_image, image=top_preloaded_images[image_index])

    # Update bottom image
    bot_image_index = (bot_image_index + 1) % len(bottom_preloaded_images)
    canvas.itemconfig(bottom_image, image=bottom_preloaded_images[bot_image_index])

    # Schedule next update (24 FPS)
    window.after(1000 // 24, update_images)

# Start the animation
update_images()

window.resizable(False, False)
window.mainloop()
