
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import subprocess
import ujson
import csv
import cv2
from PIL import Image, ImageTk
import sys
import os
import numpy as np

current_dir = os.path.dirname(os.path.abspath(__file__))

project_root = os.path.abspath(os.path.join(current_dir, '../../'))

sys.path.insert(0, project_root)

import thesystem.system

subprocess.Popen(['python', 'Files/Mod/default/sfx.py'])

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")

with open("Files/Player Data/Tabs.json",'r') as tab_son:
    tab_son_data=ujson.load(tab_son)

with open("Files/Player Data/Tabs.json",'w') as fin_tab_son:
    tab_son_data["Shop"]='Open'
    ujson.dump(tab_son_data,fin_tab_son,indent=4)

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

initial_height = 0
target_height = 756
window_width = 492

window.geometry(f"{window_width}x{initial_height}")
thesystem.system.animate_window_open(window, target_height, window_width, step=40, delay=1)

window.configure(bg = "#FFFFFF")
set_data=thesystem.misc.return_settings()
transp_value=set_data["Settings"]["Transparency"]

window.attributes('-alpha',transp_value)
window.overrideredirect(True)
window.wm_attributes("-topmost", True)

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 756,
    width = 492,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    674.0,
    653.0,
    image=image_image_1
)

with open("Files/Mod/presets.json", 'r') as pres_file:
    pres_file_data=ujson.load(pres_file)
    video_path=pres_file_data["Manwha"]["Video"]
    preloaded_frames=np.load(video_path)
player = thesystem.system.FastVideoPlayer(canvas, preloaded_frames, 277.0, 378.0, resize_factor=1.5)

def start_move(event):
    window.lastx, window.lasty = event.widget.winfo_pointerxy()

def move_window(event):
    x_root, y_root = event.widget.winfo_pointerxy()
    deltax, deltay = x_root - window.lastx, y_root - window.lasty

    if deltax != 0 or deltay != 0:  # Update only if there is actual movement
        window.geometry(f"+{window.winfo_x() + deltax}+{window.winfo_y() + deltay}")
        window.lastx, window.lasty = x_root, y_root


def ex_close(win):
    with open("Files/Player Data/Tabs.json",'r') as tab_son:
        tab_son_data=ujson.load(tab_son)

    with open("Files/Player Data/Tabs.json",'w') as fin_tab_son:
        tab_son_data["Shop"]='Close'
        ujson.dump(tab_son_data,fin_tab_son,indent=4)
    subprocess.Popen(['python', 'Files/Mod/default/sfx_close.py'])
    win.quit()

with open("Files/Player Data/Status.json", 'r') as fson:
    data=ujson.load(fson)
    lvl=data["status"][0]['level']
    coins=data["status"][0]['coins']

def open_prog(name, cat, rank, desc, value):
    if name!='-' and lvl>=5:
        with open("Files/Temp Files/Shop Temp.csv", 'w', newline='') as csv_open:
            fw=csv.writer(csv_open)
            rec=[name,cat,rank,desc,value]
            fw.writerow(rec)

        subprocess.Popen(['python', 'Manwha Version/Shop/gui1.py'])

        ex_close(window)

def sell_tab():
    if lvl>=5:
        subprocess.Popen(['python', 'Manwha Version/Shop Sell/gui1.py'])

        ex_close(window)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    245.1869659423828,
    375.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    81.0,
    56.0,
    image=image_image_3
)

'''
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=292.0,
    y=145.0,
    width=170.0,
    height=29.0
)
'''

if lvl<5:
    canvas.create_text(
        117.0,
        104.0,
        anchor="nw",
        text="[You cannot buy anything at your level]",
        fill="#FF0000",
        font=("Exo Bold", 14 * -1)
    )

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=31.0,
    y=142.0,
    width=46.26959228515625,
    height=31.702701568603516
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=81.0,
    y=142.0,
    width=46.26959228515625,
    height=31.702701568603516
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    246.0,
    432.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    245.0,
    224.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    76.0,
    224.0,
    image=image_image_6
)

canvas.create_text(
    118.0,
    193.0,
    anchor="nw",
    text="E-Rank Type Quest",
    fill="#50ABFF",
    font=("Exo Medium", 20 * -1)
)

canvas.create_text(
    118.0,
    219.0,
    anchor="nw",
    text="CATEGORY:",
    fill="#FFFFFF",
    font=("Exo Light", 13 * -1)
)

canvas.create_text(
    195.0,
    219.0,
    anchor="nw",
    text="QUEST",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

canvas.create_text(
    118.0,
    237.0,
    anchor="nw",
    text="RANK:",
    fill="#FFFFFF",
    font=("Exo Light", 13 * -1)
)

canvas.create_text(
    161.0,
    237.0,
    anchor="nw",
    text="E",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

canvas.create_text(
    376.0,
    245.0,
    anchor="nw",
    text="100",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_prog("E-Rank Type Quest", "QUEST", "E", "Quest Given to one by the System", 100),
    relief="flat"
)
button_4.place(
    x=396.0,
    y=201.0,
    width=48.0,
    height=17.0
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    245.0,
    308.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    76.0,
    308.0,
    image=image_image_8
)

canvas.create_text(
    118.0,
    277.0,
    anchor="nw",
    text="D-Rank Type Quest",
    fill="#50ABFF",
    font=("Exo Medium", 20 * -1)
)

canvas.create_text(
    118.0,
    303.0,
    anchor="nw",
    text="CATEGORY:",
    fill="#FFFFFF",
    font=("Exo Light", 13 * -1)
)

canvas.create_text(
    195.0,
    303.0,
    anchor="nw",
    text="QUEST",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

canvas.create_text(
    118.0,
    321.0,
    anchor="nw",
    text="RANK:",
    fill="#FFFFFF",
    font=("Exo Light", 13 * -1)
)

canvas.create_text(
    161.0,
    321.0,
    anchor="nw",
    text="D",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

canvas.create_text(
    376.0,
    329.0,
    anchor="nw",
    text="300",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_prog("D-Rank Type Quest", "QUEST", "D", "Quest Given to one by the System", 300),
    relief="flat"
)
button_5.place(
    x=396.0,
    y=285.0,
    width=48.0,
    height=17.0
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    245.0,
    392.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    76.0,
    392.0,
    image=image_image_10
)

canvas.create_text(
    118.0,
    361.0,
    anchor="nw",
    text="C-Rank Type Quest",
    fill="#50ABFF",
    font=("Exo Medium", 20 * -1)
)

canvas.create_text(
    118.0,
    387.0,
    anchor="nw",
    text="CATEGORY:",
    fill="#FFFFFF",
    font=("Exo Light", 13 * -1)
)

canvas.create_text(
    195.0,
    387.0,
    anchor="nw",
    text="QUEST",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

canvas.create_text(
    118.0,
    405.0,
    anchor="nw",
    text="RANK:",
    fill="#FFFFFF",
    font=("Exo Light", 13 * -1)
)

canvas.create_text(
    161.0,
    405.0,
    anchor="nw",
    text="C",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

canvas.create_text(
    376.0,
    413.0,
    anchor="nw",
    text="2700",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_prog("C-Rank Type Quest", "QUEST", "C", "Quest Given to one by the System", 2700),
    relief="flat"
)
button_6.place(
    x=396.0,
    y=369.0,
    width=48.0,
    height=17.0
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    245.0,
    476.0,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    76.0,
    476.0,
    image=image_image_12
)

canvas.create_text(
    118.0,
    445.0,
    anchor="nw",
    text="B-Rank Type Quest",
    fill="#50ABFF",
    font=("Exo Medium", 20 * -1)
)

canvas.create_text(
    118.0,
    471.0,
    anchor="nw",
    text="CATEGORY:",
    fill="#FFFFFF",
    font=("Exo Light", 13 * -1)
)

canvas.create_text(
    195.0,
    471.0,
    anchor="nw",
    text="QUEST",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

canvas.create_text(
    118.0,
    489.0,
    anchor="nw",
    text="RANK:",
    fill="#FFFFFF",
    font=("Exo Light", 13 * -1)
)

canvas.create_text(
    161.0,
    489.0,
    anchor="nw",
    text="B",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

canvas.create_text(
    376.0,
    497.0,
    anchor="nw",
    text="75000",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_prog("B-Rank Type Quest", "QUEST", "B", "Quest Given to one by the System", 75000),
    relief="flat"
)
button_7.place(
    x=396.0,
    y=453.0,
    width=48.0,
    height=17.0
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    246.0,
    560.0,
    image=image_image_13
)

image_image_14 = PhotoImage(
    file=relative_to_assets("image_14.png"))
image_14 = canvas.create_image(
    77.0,
    560.0,
    image=image_image_14
)

canvas.create_text(
    119.0,
    529.0,
    anchor="nw",
    text="A-Rank Type Quest",
    fill="#50ABFF",
    font=("Exo Medium", 20 * -1)
)

canvas.create_text(
    119.0,
    555.0,
    anchor="nw",
    text="CATEGORY:",
    fill="#FFFFFF",
    font=("Exo Light", 13 * -1)
)

canvas.create_text(
    196.0,
    555.0,
    anchor="nw",
    text="QUEST",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

canvas.create_text(
    119.0,
    573.0,
    anchor="nw",
    text="RANK:",
    fill="#FFFFFF",
    font=("Exo Light", 13 * -1)
)

canvas.create_text(
    162.0,
    573.0,
    anchor="nw",
    text="A",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

canvas.create_text(
    377.0,
    581.0,
    anchor="nw",
    text="100000",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_prog("A-Rank Type Quest", "QUEST", "A", "Quest Given to one by the System", 100000),
    relief="flat"
)
button_8.place(
    x=397.0,
    y=537.0,
    width=48.0,
    height=17.0
)

image_image_15 = PhotoImage(
    file=relative_to_assets("image_15.png"))
image_15 = canvas.create_image(
    246.0,
    644.0,
    image=image_image_15
)

image_image_16 = PhotoImage(
    file=relative_to_assets("image_16.png"))
image_16 = canvas.create_image(
    77.0,
    644.0,
    image=image_image_16
)

canvas.create_text(
    119.0,
    613.0,
    anchor="nw",
    text="S-Rank Type Quest",
    fill="#50ABFF",
    font=("Exo Medium", 20 * -1)
)

canvas.create_text(
    119.0,
    639.0,
    anchor="nw",
    text="CATEGORY:",
    fill="#FFFFFF",
    font=("Exo Light", 13 * -1)
)

canvas.create_text(
    196.0,
    639.0,
    anchor="nw",
    text="QUEST",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

canvas.create_text(
    119.0,
    657.0,
    anchor="nw",
    text="RANK:",
    fill="#FFFFFF",
    font=("Exo Light", 13 * -1)
)

canvas.create_text(
    162.0,
    657.0,
    anchor="nw",
    text="S",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

canvas.create_text(
    377.0,
    665.0,
    anchor="nw",
    text="200000",
    fill="#FFFFFF",
    font=("Exo Medium", 13 * -1)
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_prog("S-Rank Type Quest", "QUEST", "S", "Quest Given to one by the System", 200000),
    relief="flat"
)
button_9.place(
    x=397.0,
    y=621.0,
    width=48.0,
    height=17.0
)

image_image_17 = PhotoImage(
    file=relative_to_assets("image_17.png"))
image_17 = canvas.create_image(
    369.0,
    735.0,
    image=image_image_17
)

canvas.create_text(
    300.0,
    708.0,
    anchor="nw",
    text="GOLD:",
    fill="#FFD337",
    font=("Exo Regular", 20 * -1)
)

canvas.create_text(
    357.0,
    708.0,
    anchor="nw",
    text=f"{coins:07d}",
    fill="#FFD337",
    font=("Exo Bold", 20 * -1)
)

image_image_18 = PhotoImage(
    file=relative_to_assets("image_18.png"))
image_18 = canvas.create_image(
    244.0,
    10.0,
    image=image_image_18
)

canvas.tag_bind(image_18, "<ButtonPress-1>", start_move)
canvas.tag_bind(image_18, "<B1-Motion>", move_window)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: ex_close(window),
    relief="flat"
)
button_10.place(
    x=452.0,
    y=23.0,
    width=20.0,
    height=20.0
)
window.resizable(False, False)
window.mainloop()
