
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import csv
import ujson
import subprocess
import threading
import cv2
from PIL import Image, ImageTk
import sys
import os
import numpy as np

current_dir = os.path.dirname(os.path.abspath(__file__))

project_root = os.path.abspath(os.path.join(current_dir, '../../'))

sys.path.insert(0, project_root)

import thesystem.equipmentbk
import thesystem.system
import thesystem.inventory
import thesystem.equipmentbk as equipment

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")

with open("Files/Player Data/Tabs.json",'r') as tab_son:
    tab_son_data=ujson.load(tab_son)

with open("Files/Player Data/Tabs.json",'w') as fin_tab_son:
    tab_son_data["Equipment"]='Open'
    ujson.dump(tab_son_data,fin_tab_son,indent=4)

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
stop_event=threading.Event()

initial_height = 0
target_height = 555
window_width = 957

window.geometry(f"{window_width}x{initial_height}")

job=thesystem.misc.return_status()["status"][1]["job"]

top_val='dailyquest.py'
all_prev=''
video='Video'
transp_clr='#0C679B'

if job!='None':
    top_val=''
    all_prev='alt_'
    video='Alt Video'
    transp_clr='#652AA3'

thesystem.system.make_window_transparent(window,transp_clr)

with open("Files/Player Data/Settings.json", 'r') as settings_open:
    setting_data=ujson.load(settings_open)


thesystem.system.animate_window_open(window, target_height, window_width, step=50, delay=1)
window.configure(bg = "#FFFFFF")
set_data=thesystem.misc.return_settings()
transp_value=set_data["Settings"]["Transparency"]

window.attributes('-alpha',transp_value)
window.overrideredirect(True)
window.wm_attributes("-topmost", True)

top_images = f"thesystem/{all_prev}top_bar"
bottom_images = f"thesystem/{all_prev}bottom_bar"

top_preloaded_images = thesystem.system.load_or_cache_images(top_images, (970, 40), job, type_="top")
bottom_preloaded_images = thesystem.system.load_or_cache_images(bottom_images, (970, 40), job, type_="bottom")

subprocess.Popen(['python', 'Files/Mod/default/sfx.py'])

def start_move(event):
    window.lastx, window.lasty = event.widget.winfo_pointerxy()

def move_window(event):
    x_root, y_root = event.widget.winfo_pointerxy()
    deltax, deltay = x_root - window.lastx, y_root - window.lasty

    if deltax != 0 or deltay != 0:  # Update only if there is actual movement
        window.geometry(f"+{window.winfo_x() + deltax}+{window.winfo_y() + deltay}")
        window.lastx, window.lasty = x_root, y_root


def ex_close():
    if setting_data["Settings"]["Performernce (ANIME):"] != "True":
        stop_event.set()
        update_thread.join()
    with open("Files/Player Data/Tabs.json",'r') as tab_son:
        tab_son_data=ujson.load(tab_son)

    if tab_son_data["Equipment"]=='Open':

        with open("Files/Player Data/Tabs.json",'w') as fin_tab_son:
            tab_son_data["Equipment"]='Close'
            ujson.dump(tab_son_data,fin_tab_son,indent=4)

    threading.Thread(target=thesystem.system.fade_out, args=(window, 0.8)).start()
    subprocess.Popen(['python', 'Files/Mod/default/sfx_close.py'])
    thesystem.system.animate_window_close(window, 0, window_width, step=20, delay=1)

def split_text(text, segment_length):
    # Check if the text length exceeds the segment length
    if len(text) > segment_length:
        # Find the last space within the segment length to avoid splitting a word
        split_point = text.rfind(" ", 0, segment_length)
        
        # If there's no space, we have to split at the exact segment length
        if split_point == -1:
            split_point = segment_length
        
        # Split text at the identified point
        part1 = text[:split_point]
        part2 = text[split_point:].lstrip()  # Remove leading spaces in part2
    else:
        # If text is within the segment length, assign it all to part1 and leave part2 empty
        part1 = text
        part2 = ""
    
    return part1, part2

def open_select(cat):
    fout=open('Files/Temp Files/Equipment Temp.csv', 'w', newline='')
    fw=csv.writer(fout)
    rec=[cat]
    fw.writerow(rec)
    fout.close()

    subprocess.Popen(['python', 'Anime Version/Equip Item/gui.py'])

    ex_close()

def set_effect_open():
    subprocess.Popen(['python', 'Anime Version/Set Effects/gui.py'])

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 555,
    width = 957,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    478.0,
    277.0,
    image=image_image_1
)

with open("Files/Mod/presets.json", 'r') as pres_file:
    pres_file_data=ujson.load(pres_file)
    video_path=pres_file_data["Anime"][video]
    preloaded_frames=np.load(video_path)
player = thesystem.system.FastVideoPlayer(canvas, preloaded_frames, 478.0, 277.0, pause_duration=0.3)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    469.9760437011719,
    276.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    477.0,
    287.9999999999999,
    image=image_image_3
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    212.0,
    115.0,
    image=image_image_5
)

# ! ============================================================================
# ! Title
# ! ============================================================================

canvas.create_text(
    136.0,
    97.0,
    anchor="nw",
    text="EQUIPMENT",
    fill="#FFFFFF",
    font=("Montserrat SemiBold", 24 * -1)
)

# ! ============================================================================
# ! INFO ujson RETREVAL
# ! ============================================================================

helm = chest = f_gaun = s_gaun = boot = ring = collar = '-'
helmboost_1 = helmboost_2 = ''
chestboost_1 = chestboost_2 = ''
f_gaunboost_1 = f_gaunboost_2 = ''
s_gaunboost_1 = s_gaunboost_2 = ''
bootboost_1 = bootboost_2 = ''
ringboost_1 = ringboost_2 = ''
collarboost_1 = collarboost_2 = ''

max_width, max_height = 164/1.5, 126/1.5

def assign_equipment(equipment_list):
    global helm, chest, f_gaun, s_gaun, boot, ring, collar
    global helmboost_1, helmboost_2, chestboost_1, chestboost_2
    global f_gaunboost_1, f_gaunboost_2, s_gaunboost_1, s_gaunboost_2
    global bootboost_1, bootboost_2, ringboost_1, ringboost_2
    global collarboost_1, collarboost_2

    # Unpack equipment items and boosts from the list
    equipment_items, equipment_boosts = equipment_list

    # Assign values to the equipment variables
    helm, chest, f_gaun, s_gaun, boot, ring, collar = equipment_items
    helmboost_1, helmboost_2, chestboost_1, chestboost_2, f_gaunboost_1, f_gaunboost_2, s_gaunboost_1, s_gaunboost_2, bootboost_1, bootboost_2, ringboost_1, ringboost_2, collarboost_1, collarboost_2 = equipment_boosts

equipment_list=equipment.get_equipment()
assign_equipment(equipment_list)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    479.0,
    278.0,
    image=image_image_4
)

boot_image = (thesystem.equipmentbk.get_armor_image(boot))
boot_im = canvas.create_image(
    479.0,
    278.0,
    image=boot_image
)

sgaun_image = (thesystem.equipmentbk.get_armor_image(s_gaun))
sgaun_im = canvas.create_image(
    479.0,
    278.0,
    image=sgaun_image
)

fgaun_image = (thesystem.equipmentbk.get_armor_image(f_gaun))
fgaun_im = canvas.create_image(
    479.0,
    278.0,
    image=fgaun_image
)

ring_image = (thesystem.equipmentbk.get_armor_image(ring))
ring_im = canvas.create_image(
    479.0,
    278.0,
    image=ring_image
)

helm_image = (thesystem.equipmentbk.get_armor_image(helm))
helm_im = canvas.create_image(
    479.0,
    278.0,
    image=helm_image
)

chest_image = (thesystem.equipmentbk.get_armor_image(chest))
chest_im = canvas.create_image(
    479.0,
    278.0,
    image=chest_image
)

collar_image = (thesystem.equipmentbk.get_armor_image(collar))
collar_im = canvas.create_image(
    479.0,
    278.0,
    image=collar_image
)

# ? ====================================================================
# ? Helmet Part
# ? ====================================================================

image_image_6 = thesystem.inventory.get_item_button_image(helm, max_width, max_height)
image_6 = canvas.create_image(
    164.0,
    189.0,
    image=image_image_6
)

canvas.create_text(
    211.0,
    182.0,
    anchor="nw",
    text=helm,
    fill="#FFFFFF",
    font=("Montserrat Regular", 11 * -1)
)

canvas.create_text(
    211.0,
    196.0,
    anchor="nw",
    text='-'+helmboost_1,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

canvas.create_text(
    211.0,
    212.0,
    anchor="nw",
    text='-'+helmboost_2,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_select("HELM"),
    relief="flat"
)
button_1.place(
    x=208.0,
    y=167.0,
    width=12.0,
    height=12.0
)

# ? ====================================================================
# ? Chestplate Part
# ? ====================================================================

image_image_7 = thesystem.inventory.get_item_button_image(chest, max_width, max_height)
image_7 = canvas.create_image(
    262.0,
    285.0,
    image=image_image_7
)

canvas.create_text(
    96.0,
    267.0,
    anchor="nw",
    text=chest,
    fill="#FFFFFF",
    font=("Montserrat Regular", 11 * -1)
)

canvas.create_text(
    96.0,
    284.0,
    anchor="nw",
    text='-'+chestboost_1,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

canvas.create_text(
    96.0,
    302.0,
    anchor="nw",
    text='-'+chestboost_2,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_select("CHESTPLATE"),
    relief="flat"
)
button_2.place(
    x=305.0,
    y=252.0,
    width=12.0,
    height=12.0
)

# ? ====================================================================
# ? First Gauntlet Part
# ? ====================================================================

image_image_8 = thesystem.inventory.get_item_button_image(f_gaun, max_width, max_height)
image_8 = canvas.create_image(
    164.0,
    381.0,
    image=image_image_8
)

canvas.create_text(
    208.0,
    363.0,
    anchor="nw",
    text=f_gaun,
    fill="#FFFFFF",
    font=("Montserrat Regular", 11 * -1)
)

canvas.create_text(
    208.0,
    380.0,
    anchor="nw",
    text='-'+f_gaunboost_1,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

canvas.create_text(
    208.0,
    395.0,
    anchor="nw",
    text='-'+f_gaunboost_2,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_select("FIRST GAUNTLET"),
    relief="flat"
)
button_3.place(
    x=207.0,
    y=346.0,
    width=12.0,
    height=12.0
)

# ? ====================================================================
# ? Boots Part
# ? ====================================================================

image_image_9 = thesystem.inventory.get_item_button_image(boot, max_width, max_height)
image_9 = canvas.create_image(
    807.0,
    418.0,
    image=image_image_9
)

canvas.create_text(
    655.0,
    408.0,
    anchor="nw",
    text=boot,
    fill="#FFFFFF",
    font=("Montserrat Regular", 11 * -1)
)

canvas.create_text(
    655.0,
    421.0,
    anchor="nw",
    text='-'+bootboost_1,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

canvas.create_text(
    655.0,
    436.0,
    anchor="nw",
    text='-'+bootboost_2,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_select("BOOTS"),
    relief="flat"
)
button_4.place(
    x=753.0,
    y=394.0,
    width=12.0,
    height=12.0
)

# ? ====================================================================
# ? Collar Part
# ? ====================================================================

image_image_10 = thesystem.inventory.get_item_button_image(collar, max_width, max_height)
image_10 = canvas.create_image(
    806.0,
    125.0,
    image=image_image_10
)

segment_length = 30
col_part1, col_part2 = split_text(collar, segment_length)

if len(collar)<30:
    canvas.create_text(
        654.0,
        110.0,
        anchor="nw",
        text=collar,
        fill="#FFFFFF",
        font=("Montserrat Regular", 11 * -1)
    )

else:
    canvas.create_text(
        654.0,
        110.0,
        anchor="nw",
        text=col_part1,
        fill="#FFFFFF",
        font=("Montserrat Regular", 11 * -1)
    )

    canvas.create_text(
        654.0,
        110.0+10,
        anchor="nw",
        text=col_part2,
        fill="#FFFFFF",
        font=("Montserrat Regular", 11 * -1)
    )

canvas.create_text(
    654.0,
    126.0+5,
    anchor="nw",
    text='-'+collarboost_1,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

canvas.create_text(
    654.0,
    142.0+5,
    anchor="nw",
    text='-'+collarboost_2,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_select("COLLAR"),
    relief="flat"
)
button_5.place(
    x=752.0,
    y=98.0,
    width=12.0,
    height=12.0
)

# ? ====================================================================
# ? Ring Part
# ? ====================================================================

image_image_11 = thesystem.inventory.get_item_button_image(ring, max_width, max_height)
image_11 = canvas.create_image(
    684.0,
    318.0,
    image=image_image_11
)

canvas.create_text(
    730.0,
    295.0,
    anchor="nw",
    text=ring,
    fill="#FFFFFF",
    font=("Montserrat Regular", 11 * -1)
)

canvas.create_text(
    730.0,
    308.0,
    anchor="nw",
    text='-'+ringboost_1,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

canvas.create_text(
    730.0,
    322.0,
    anchor="nw",
    text='-'+ringboost_2,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_select("RING"),
    relief="flat"
)
button_6.place(
    x=627.0,
    y=280.0,
    width=12.0,
    height=12.0
)

# ? ====================================================================
# ? Second Gauntlet Part
# ? ====================================================================

image_image_12 = thesystem.inventory.get_item_button_image(s_gaun, max_width, max_height)
image_12 = canvas.create_image(
    684.0,
    226.0,
    image=image_image_12
)

segment_length = 30
s_gpart1, s_gpart2 = split_text(s_gaun, segment_length)

if len(s_gaun)<31:
    canvas.create_text(
        730.0,
        202.0,
        anchor="nw",
        text=s_gaun,
        fill="#FFFFFF",
        font=("Montserrat Regular", 11 * -1)
    )

else:
    canvas.create_text(
        730.0,
        202.0,
        anchor="nw",
        text=s_gpart1,
        fill="#FFFFFF",
        font=("Montserrat Regular", 11 * -1)
    )

    canvas.create_text(
        730.0,
        214.0,
        anchor="nw",
        text=s_gpart2,
        fill="#FFFFFF",
        font=("Montserrat Regular", 11 * -1)
    )

canvas.create_text(
    730.0,
    215.0+12,
    anchor="nw",
    text='-'+s_gaunboost_1,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

canvas.create_text(
    730.0,
    230.0+12,
    anchor="nw",
    text='-'+s_gaunboost_2,
    fill="#69FF44",
    font=("Montserrat Regular", 12 * -1)
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_select("SECOND GAUNTLET"),
    relief="flat"
)
button_7.place(
    x=628.0,
    y=190.0,
    width=12.0,
    height=12.0
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    332.0,
    150.38160705566406,
    image=image_image_13
)

image_image_14 = PhotoImage(
    file=relative_to_assets("image_14.png"))
image_14 = canvas.create_image(
    376.0,
    256.0,
    image=image_image_14
)

image_image_15 = PhotoImage(
    file=relative_to_assets("image_15.png"))
image_15 = canvas.create_image(
    292.0,
    326.88160705566406,
    image=image_image_15
)

image_image_16 = PhotoImage(
    file=relative_to_assets("image_16.png"))
image_16 = canvas.create_image(
    332.0,
    150.38160705566406,
    image=image_image_16
)

image_image_17 = PhotoImage(
    file=relative_to_assets("image_17.png"))
image_17 = canvas.create_image(
    630.0,
    125.0,
    image=image_image_17
)

image_image_18 = PhotoImage(
    file=relative_to_assets("image_18.png"))
image_18 = canvas.create_image(
    603.0160522460938,
    223.0,
    image=image_image_18
)

image_image_19 = PhotoImage(
    file=relative_to_assets("image_19.png"))
image_19 = canvas.create_image(
    605.908523776442,
    327.5000013367189,
    image=image_image_19
)

image_image_20 = PhotoImage(
    file=relative_to_assets("image_20.png"))
image_20 = canvas.create_image(
    639.9093198482187,
    375.92901396502793,
    image=image_image_20
)
'''
button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=set_effect_open,
    relief="flat"
)
button_8.place(
    x=420.0,
    y=466.0,
    width=114.0,
    height=15.0
)

image_0=canvas.create_rectangle(
    0.0,
    0.0,
    960.0,
    37.0,
    fill="#2E2E2E",
    outline="")

canvas.tag_bind(image_0, "<ButtonPress-1>", start_move)
canvas.tag_bind(image_0, "<B1-Motion>", move_window)

button_image_26 = PhotoImage(
    file=relative_to_assets("button_0.png"))
button_26 = Button(
    image=button_image_26,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: ex_close(),
    relief="flat"
)
button_26.place(
    x=920.0,
    y=4.0,
    width=28.0,
    height=28.0
)

'''


side = PhotoImage(file=relative_to_assets("blue.png"))
if job.upper()!="NONE":
    side = PhotoImage(file=relative_to_assets("purple.png"))
canvas.create_image(36.0, 275.0, image=side)
canvas.create_image(926.0, 290.0, image=side)

canvas.create_rectangle(
    0.0,
    0.0,
    101.0,
    21.0,
    fill=transp_clr,
    outline="")

canvas.create_rectangle(
    0.0,
    520.0,
    1000.0,
    716.0,
    fill=transp_clr,
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    1000.0,
    34.0,
    fill=transp_clr,
    outline="")

image_40 = thesystem.system.side_bar("left_bar.png", (101, 500))
canvas.create_image(36.0, 275.0, image=image_40)

image_50 = thesystem.system.side_bar("right_bar.png", (80, 505))
canvas.create_image(910.0, 278.0, image=image_50)

image_index = 0
bot_image_index = 0

top_image = canvas.create_image(
    472.0,
    20.0,
    image=top_preloaded_images[image_index]
)

canvas.tag_bind(top_image, "<ButtonPress-1>", start_move)
canvas.tag_bind(top_image, "<B1-Motion>", move_window)

bottom_image = canvas.create_image(
    470.0,
    530.0,
    image=bottom_preloaded_images[bot_image_index]
)

step,delay=1,1

def update_images():
    global image_index, bot_image_index

    image_index = (image_index + 1) % len(top_preloaded_images)
    top_img = top_preloaded_images[image_index]
    canvas.itemconfig(top_image, image=top_img)
    canvas.top_img = top_img

    bot_image_index = (bot_image_index + 1) % len(bottom_preloaded_images)
    bot_img = bottom_preloaded_images[bot_image_index]
    canvas.itemconfig(bottom_image, image=bot_img)
    canvas.bot_img = bot_img

    window.after(1000 // 24, update_images)

# Start the animation
if setting_data["Settings"]["Performernce (ANIME):"] != "True":
    update_thread = threading.Thread(target=update_images)
    update_thread.start()

# ===========================================================

image_image_25 = PhotoImage(
    file=relative_to_assets("image_25.png"))
image_25 = canvas.create_image(
    318.0,
    108.0,
    image=image_image_25
)

canvas.tag_bind(image_25, "<ButtonPress-1>", lambda event: thesystem.system.info_open("Equipment"))

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: ex_close(),
    relief="flat"
)
button_9.place(
    x=838.0,
    y=57.0,
    width=26.0,
    height=26.0
)

window.resizable(False, False)
window.mainloop()
